---
- name: eliminar cuenta de usuario en RHEL
  hosts: "{{ server }}"
  tasks:
    - name: eliminar cuenta de usuario
      user:
        name: "{{ usuario }}"
        state: absent
        remove: yes
