---
- name: eliminar cuenta de usuario en RHEL
  hosts: "{{ server }}"
  become: yes
  tasks:
    - name: eliminar cuenta de usuario
      user:
        name: "{{ usuario }}"
        state: absent
        remove: yes
    - name: muestra resultado
      debug:
        msg: "se ha eliminado correctamente el usuario "{{ usuario }}" "
