---
- name: cargar certificado
  hosts: ipamserv
  gather_facts: false

  tasks:
    - name: mostrar archivo
      ansible.builtin.debug:
        msg: "{{ contenido_archivo_data }}"
    - name: obtiene el contenido del archvio
      copy:
        content: "{{ contenido_archivo_data }}"
        dest: /home/poc_ansible/archivo_copiado_ok.txt
    - name: lista directorio 
      command: ls /home/poc_ansible
      register: "{{ lista_directorio}}"

    - name: muestra contenido directorio
      debug:
        msg: "{{ lista_directorio.stdout }}"
