---
- name: cargar certificado
  hosts: "{{ server }}"
  gather_facts: false

  tasks:
    - name: mostrar certificado
      ansible.builtin.debug:
        msg: "{{ cert_data }}"
    - name: Render out the certificate file somewhere
      copy:
        content: "{{ cert_data }}"
        dest: /opt/server_certificates/certificate.cer
