---
- name: copia archivo directamente
  hosts: "{{ origen }}"
  vars:
    server_origen: "{{ origen }}"
    server_destino: "{{ destino }}"
  tasks:
  - name: copiar archivo con scp
    command: scp /home/poc_ansible/ansible.txt poc_ansible@"{{ destino }}":/home/poc_ansible/
   
  
  
#  - name:  Synchronization using rsync protocol on delegate host (push)
#    ansible.posix.synchronize:
#      src: /home/poc_ansible/ansible.txt
#      dest: /home/poc_ansible/
#    delegate_to: "{{ destino }}"
  
#    - name: leer archivo desde server_origen a server_destino
#      fetch:
#        src: /home/poc_ansible/ansible.txt
#        dest: buffer/
#        flat: yes
#        remote_src: true
#      run_once: yes
#      when: inventory_hostname == server_origen

#    - name: copiar el archivo desde server_origen a server_destino 
#      copy:
#        src: buffer/ansible.txt
#        dest: /home/poc_ansible/ansible.txt
#        remote_src: true
#      when: inventory_hostname == server_destino
