---
- name: Crear cuenta de usuario en Ubuntu
  hosts: "{{ server }}"
  become: yes

  tasks:
    - name: Agregar el usuario
      user:
        name: "{{ username }}"
        shell: /bin/bash
        home: "/home/{{ username }}"
        password: "{{ password | password_hash('sha512') }}"  
        state: present

   
