---
- name: Crear cuenta de usuario en Ubuntu
  hosts: tu_servidor
  become: yes

  tasks:
    - name: Crear el directorio home del usuario
      file:
        path: "/home/{{ username }}"
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0755'

    - name: Agregar el usuario
      user:
        name: "{{ username }}"
        shell: /bin/bash
        home: "/home/{{ username }}"
        password: "{{ password | password_hash('sha512') }}"  # Recuerda cambiar 'password' por la contraseña deseada
        state: present

   
