---
- name: Crear cuentas de usuario en RHEL
  hosts: "{{ servers }}"
  become: yes  
  vars: 
    random_password: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters,digits,punctuation') }}"
  
  tasks:    
    - name: Crear cuentas de usuario
      user:
        name: "{{ nombre }}"
        password: "{{ random_password | password_hash('sha512') }}"  
        state: present 
    - name: Mostrar en pantalla contraseña
      debug:
        msg: la contraseña creada para "{{ nombre }}" es "{{ random_password }}"
