---
- name: Crear cuentas de usuario en RHEL
  hosts: "{{ servers }}"
  become: yes  

  
  tasks:
   - name: Generar una contraseña aleatoria
      set_fact:
        random_password: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters,digits,punctuation') | password_hash('sha512') }}"
    
    - name: Crear cuentas de usuario
      user:
        name: "{{ nombre }}"
        password: "{{ random_pasword | password_hash('sha512') }}"  
        state: present 
     - name: Mostrar en pantalla contraseña
       debug:
         msg: la contraseña creada para "{{ nombre }}" es "{{ random_password }}"
