---
- name: Crear cuentas de usuario en RHEL
  hosts: "{{ servers }}"
  become: yes  

  
  tasks:
    - name: Crear cuentas de usuario
      user:
        name: "{{ nombre }}"
        password: "{{ password | password_hash('sha512') }}"  
        state: present 
