---
- name: Leer archivo en RHEL
  hosts: autmplataformas
  tasks:
    - name: Leer el contenido del archivo
      ansible.builtin.slurp:
        path: /home/poc_ansible/ansible.txt
      register: contenido_archivo

    - name: Mostrar el contenido del archivo
      ansible.builtin.debug:
        msg:  {{ contenido_archivo.content }}
    - name: pasar al workflow
      ansible.builtin.set_stats:
        data: 
          csr_data: "{{ contenido_archivo.content }}"
