---
- name: Listar cuentas de usuario en RHEL
  hosts: "{{ servers }}"
  gather_facts: no
  tasks:
    - name: Listar cuentas de usuario
      raw: "awk -F: '$3 >= 500 {print $1}' /etc/passwd"
      register: cuentas_de_usuario

    - name: Mostrar resultado
      debug:
        msg: "{{ cuentas_de_usuario.stdout_lines }}"
